# -*- coding: utf-8 -*-
from ..server.system import Server
from ..client.system import Client

def isServer() -> bool: ...
    
def getServerSystem() -> Server: ...

def getClientSystem() -> Client: ...

def getSystem() -> Server | Client: ...
