from typing import Literal, overload

from mod.common.minecraftEnum import EntityComponentType, RayFilterType
from Effect import *
from ...interfaces.BlockOptions import *
from ...interfaces.AnimeOptions import *
from ...interfaces.EntityOptions import *
from ...interfaces.TeleportOptions import *
from ...interfaces.Raycasts import *
from ...enums.Dimension import *
from .components.EntityComponents import *
from Command import *
from Player import Player

class Entity(object):
    """
    Represents the state of an entity (a mob, the player, or other moving objects like mine carts) in the world.
    """
    @property
    def id(self) -> str: ...
    @property
    def isValid(self) -> bool: ...
    @property
    def dimension(self) -> Dimension: ...
    @property
    def isClimbing(self) -> bool: ...
    @property
    def isFalling(self) -> bool: ...
    @property
    def isInWater(self) -> bool: ...
    @property
    def isOnGround(self) -> bool: ...
    @property
    def isSleeping(self) -> bool: ...
    @property
    def isSitting(self) -> bool: ...
    @property
    def isSneaking(self) -> bool: ...
    @property
    def isSprinting(self) -> bool: ...
    @property
    def isSwimming(self) -> bool: ...
    @property
    def location(self) -> Vector3: ...
    @property
    def nameTag(self) -> str: ...
    @nameTag.setter
    def nameTag(self, name: str) -> None: ...
    @property
    def health(self): ...
    @health.setter
    def health(self, value): ...
    @property
    def scoreboardIdentity(self): ...
    @property
    def typeId(self) -> str: ...
    def addEffect(self, effectType: 'str|EffectType', duration: int, options: 'EntityEffectOptions|dict'=None) -> 'Effect': ...
    def addTag(self, tag: str) -> bool: ...
    def applyDamage(self, amount: int, options: 'dict|EntityApplyDamageByProjectileOptions|EntityApplyDamageOptions'={}) -> bool: ...
    def applyImpulse(self, vector: 'Vector3') -> None: ...
    def applyKnockback(self, horizontalForce: 'VectorXZ', verticalStrength: float) -> None: ...
    def clearDynamicProperties(self) -> None: ...
    def clearVelocity(self) -> None: ...
    def extinguishFire(self, useEffects: bool=True) -> bool: ...
    def getBlockFromViewDirection(self, options: 'dict|BlockRaycastOptions'=None) -> 'BlockRaycastHit': ...
    @overload
    def getComponent(self, componentId: Literal['equippable'] | Literal['minecraft:equippable']) -> 'EntityEquippableComponent': ...
    @overload
    def getComponent(self, componentId: Literal['health'] | Literal['minecraft:health']) -> 'EntityHealthComponent': ...
    @overload
    def getComponent(self, componentId: Literal['lava_movement'] | Literal['minecraft:lava_movement']) -> 'EntityLavaMovementComponent': ...
    @overload
    def getComponent(self, componentId: Literal['movement'] | Literal['minecraft:movement']) -> 'EntityMovementComponent': ...
    @overload
    def getComponent(self, componentId: Literal['movement.jump'] | Literal['minecraft:movement.jump']) -> 'EntityJumpComponent': ...
    @overload
    def getComponent(self, componentId: Literal['underwater_movement'] | Literal['minecraft:underwater_movement']) -> 'EntityUnderwaterMovementComponent': ...
    @overload
    def getComponent(self, componentId: Literal['inventory'] | Literal['minecraft:inventory']) -> 'EntityInventoryComponent': ...
    @overload
    def getComponent(self, componentId: str) -> 'EntityComponent|None': ...
    def getComponents(self) -> 'list[EntityComponent]': ...
    def getDynamicProperty(self, identifier: str): ...
    def getDynamicPropertyIds(self) -> 'list[str]': ...
    def getDynamicPropertyTotalByteCount(self) -> int: ...
    def getEffect(self, effectType: 'str|EffectType') -> 'Effect': ...
    def getEffects(self) -> 'list[Effect]': ...
    def getEntitiesFromViewDirection(self, options: 'dict'=None) -> 'list[EntityRaycastHit]': ...
    def getHeadLocation(self) -> 'Vector3': ...
    def getRotation(self) -> 'Vector2': ...
    def getTags(self) -> 'list[str]': ...
    def getVelocity(self) -> 'Vector3': ...
    def getProperty(self, identifier: str): ...
    def getViewDirection(self) -> 'Vector3': ...
    def getFamilies(self): ...
    def hasComponent(self, componentId: str) -> bool: ...
    def hasTag(self, tag: str) -> bool: ...
    def hasTarget(self) -> bool: ...
    def getTarget(self): ...
    def hasFamily(self, familyName: str) -> bool: ...
    def kill(self) -> bool: ...
    def getNbt(self) -> dict: ...
    def matches(self, options: 'dict'=None) -> bool: ...
    def playAnimation(self, animationName: str, options: 'dict|PlayAnimationOptions'={}) -> None: ...
    def remove(self) -> None: ...
    def removeEffect(self, effectType: 'str|EffectType') -> bool: ...
    def removeTag(self, tag: str) -> bool: ...
    def resetProperty(self, identifier: str): ...
    def runCommand(self, commandString: str) -> CommandResult: ...
    def setDynamicProperty(self, identifier: str, value) -> None: ...
    def setOnFire(self, seconds: int, useEffects: bool=True) -> bool: ...
    def setProperty(self, identifier: str, value) -> None: ...
    def setRotation(self, rotation: 'Vector2') -> None: ...
    def teleport(self, location: 'Vector3', teleportOptions: 'dict|TeleportOptions'={}) -> None: ...
    def triggerEvent(self, eventName: str) -> None: ...
    def tryTeleport(self, location: 'Vector3', teleportOptions: 'dict'=None) -> bool: ...
    def asPlayer(self) -> Player: ...

def createEntity(entityId) -> Entity | Player | None: ...
