import mod.client.extraClientApi as clientApi
compClient = clientApi.GetEngineCompFactory()
levelId = clientApi.GetLevelId()
localPlayerId = clientApi.GetLocalPlayerId()

class LevelClient:
    localPlayer = compClient.CreatePlayer(levelId)
    achievement = compClient.CreateAchievement(levelId)
    actorRender = compClient.CreateActorRender(levelId)
    biome = compClient.CreateBiome(levelId)
    block = compClient.CreateBlock(levelId)
    blockGeometry = compClient.CreateBlockGeometry(levelId)
    blockInfo = compClient.CreateBlockInfo(levelId)
    blockUseEventWhiteList = compClient.CreateBlockUseEventWhiteList(levelId)
    camera = compClient.CreateCamera(levelId)
    chunkSource = compClient.CreateChunkSource(levelId)
    configClient = compClient.CreateConfigClient(levelId)
    customAudio = compClient.CreateCustomAudio(levelId)
    dimension = compClient.CreateDimension(levelId)
    drawing = compClient.CreateDrawing(levelId)
    fog = compClient.CreateFog(levelId)
    game = compClient.CreateGame(levelId)
    model = compClient.CreateModel(levelId)
    neteaseShop = compClient.CreateNeteaseShop(levelId)
    operation = compClient.CreateOperation(levelId)
    playerView = compClient.CreatePlayerView(levelId)
    postProcess = compClient.CreatePostProcess(levelId)
    recipe = compClient.CreateRecipe(levelId)
    skyRender = compClient.CreateSkyRender(levelId)
    textBoard = compClient.CreateTextBoard(levelId)
    textNotify = compClient.CreateTextNotifyClient(levelId)
    virtualWorld = compClient.CreateVirtualWorld(levelId)